//- Keys to all the strings in languages.js
export default {
  //- Layer Labels
  GAIN_LABEL: 'GAIN_LABEL',
  GAIN_SUB_LABEL: 'GAIN_SUB_LABEL',
  LOSS_LABEL: 'LOSS_LABEL',
  LOSS_SUB_LABEL: 'LOSS_SUB_LABEL',
  ACTIVE_FIRES_LABEL: 'ACTIVE_FIRES_LABEL',
  ACTIVE_FIRES_SUB_LABEL: 'ACTIVE_FIRES_SUB_LABEL',
  TREE_COVER_LABEL: 'TREE_COVER_LABEL',
  TREE_COVER_SUB_LABEL: 'TREE_COVER_SUB_LABEL',
  LAND_COVER_LABEL: 'LAND_COVER_LABEL',
  IFL_LABEL: 'IFL_LABEL',
  CARBON_LABEL: 'CARBON_LABEL',
  //- Navigation Items
  NAV_ABOUT: 'NAV_ABOUT',
  NAV_DOWNLOAD: 'NAV_DOWNLOAD',
  NAV_MAP_THEMES: 'NAV_MAP_THEMES',
  //- Analysis Items
  ANALYSIS_INSTRUCTION_HEADER: 'ANALYSIS_INSTRUCTION_HEADER',
  ANALYSIS_INSTRUCTION_LIST: 'ANALYSIS_INSTRUCTION_LIST',
  ANALYSIS_OR: 'ANALYSIS_OR',
  ANALYSIS_DRAW_INSTRUCTIONS: 'ANALYSIS_DRAW_INSTRUCTIONS',
  ANALYSIS_DRAW_BUTTON: 'ANALYSIS_DRAW_BUTTON',
  ANALYSIS_SHAPEFILE_UPLOAD: 'ANALYSIS_SHAPEFILE_UPLOAD',
  ANALYSIS_SELECT_TYPE_LABEL: 'ANALYSIS_SELECT_TYPE_LABEL',
  ANALYSIS_SELECT_TYPE_OPTIONS: 'ANALYSIS_SELECT_TYPE_OPTIONS',
  ANALYSIS_GROUP_RESTORATION: 'ANALYSIS_GROUP_RESTORATION',
  ANALYSIS_GROUP_SLOPE: 'ANALYSIS_GROUP_SLOPE',
  ANALYSIS_GROUP_OTHER: 'ANALYSIS_GROUP_OTHER'
};
